DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 250
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224) 
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "adamw"
  LR: 0.001
  MAX_EPOCH: 1
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 0
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 20

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  PromptLT:
    PREC: "amp"
    N_REP_TOKENS: 5
    SHARED_LAYERS: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    SHARED_DIM: 32